#  SPDX-License-Identifier: BSD-3-Clause
#  Copyright (C) 2015 Intel Corporation.
#  All rights reserved.
#

# SPDK_ROOT_DIR := /home/pgmabv/spdk
SPDK_ROOT_DIR := /home/ec2-user/spdk

# APP = hello_world
APP = $(CURDIR)/hello_world

include $(SPDK_ROOT_DIR)/mk/nvme.libtest.mk
